import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import connectToDatabase from "../pages/mongdb";
// 调用函数以连接到数据库
connectToDatabase();

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "硕磐智能",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
